services:
  nginx:
    container_name: nginx
    hostname: nginx
    image: private-registry.nginx.com/nginx-plus/base:r34-debian-bookworm
    # image: nginx:mainline-bookworm
    # build: nginx          # Build new container, using /nginx/Dockerfile
    volumes:
        - ./nginx/conf.d:/etc/nginx/conf.d                    # Copy all config files to container's conf.d directory
        - ./nginx/ssl/nginx-plus.jwt:/etc/nginx/license.jwt   # Copy JWT Token from parent folder to container to fulfill licensing requirement
    restart: always
    ports:
      - "80:80"
      - "8080:8080"

  vampi:
    container_name: vampi
    hostname: vampi_server1
    image: erev0s/vampi
    environment:
      - tokentimetolive=300
    restart: always
    ports:
      - "5000:5000"

  juiceshop:
    container_name: juiceshop
    hostname: juiceshop_server1
    image: bkimminich/juice-shop
    restart: always
    ports:
      - "3000:3000"