services:
  "httpbin1":
    container_name: httpbin
    image: kennethreitz/httpbin
    restart: always
    ports:
      - "3001:80"
      - "3002:80"

  vampi:
    container_name: vampi
    hostname: vampi_server1
    image: erev0s/vampi
    restart: always
    ports:
      - "80:5000"

  juiceshop:
    container_name: juiceshop
    hostname: juiceshop_server1
    image: bkimminich/juice-shop
    restart: always
    ports:
      - "3000:3000"