services:
  nginx:
    container_name: nginx
    hostname: nginx
    image: private-registry.nginx.com/nginx-plus/base:r34-debian-bookworm
    # image: nginx:mainline-bookworm
    # build: nginx          # Build new container, using /nginx/Dockerfile
    volumes:
        - ./nginx/conf.d:/etc/nginx/conf.d            # Copy all config files to container's conf.d directory
    restart: always
    ports:
      - "80:80"
      - "8080:8080"

  httpbin1:
    container_name: httpbin
    hostname: httpbin_server1
    image: kennethreitz/httpbin
    restart: always
    ports:
      - "3001:80"
      - "3002:80"

  vampi:
    container_name: vampi
    hostname: vampi_server1
    image: erev0s/vampi
    restart: always
    ports:
      - "5000:5000"

  vampi2:
    container_name: vampi2
    hostname: vampi_server2
    image: erev0s/vampi
    restart: always
    ports:
      - "5001:5000"

  juiceshop:
    container_name: juiceshop
    hostname: juiceshop_server1
    image: bkimminich/juice-shop
    restart: always
    ports:
      - "3000:3000"