apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-ingress
  namespace: nginx-ingress
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx-ingress
  template:
    metadata:
      labels:
        app: nginx-ingress
      annotations:
        prometheus.io/scrape: "true" #uncommented
        prometheus.io/port: "9113"   #uncommented
        #prometheus.io/scheme: http
    spec:
      serviceAccountName: nginx-ingress
      containers:
      - image: 664341837355.dkr.ecr.us-east-1.amazonaws.com/shouvik/nginx-plus-ingress:2.1.0
        imagePullPolicy: IfNotPresent
        name: nginx-plus-ingress
        ports:
        - name: http
          containerPort: 80
        - name: https
          containerPort: 443
        - name: readiness-port
          containerPort: 8081
        - name: dashboard #added
          containerPort: 9000
        - name: prometheus
          containerPort: 9113
        # readinessProbe: #commented out
        #   httpGet:
        #     path: /nginx-ready
        #     port: readiness-port
        #   periodSeconds: 1
        securityContext:
          allowPrivilegeEscalation: true
          runAsUser: 101 #nginx
          capabilities:
            drop:
            - ALL
            add:
            - NET_BIND_SERVICE
        env:
        - name: POD_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        - name: POD_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        args:
          - -nginx-plus
          - -nginx-configmaps=$(POD_NAMESPACE)/nginx-config
          - -default-server-tls-secret=$(POD_NAMESPACE)/default-server-secret
          - -nginx-status-port=9000 #added
          - -nginx-status-allow-cidrs=0.0.0.0/0 #added
         #- -enable-app-protect
         #- -enable-app-protect-dos
         #- -v=3 # Enables extensive logging. Useful for troubleshooting.
          - -report-ingress-status #uncommented
         #- -external-service=nginx-ingress
          - -enable-prometheus-metrics #uncommented
          - -enable-latency-metrics #added
         #- -global-configuration=$(POD_NAMESPACE)/nginx-configuration
      imagePullSecrets:
          - name: dockersecret