apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: nginx-echo
  name: nginx-echo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx-echo
  template:
    metadata:
      labels:
        app: nginx-echo
    spec:
      containers:
      - image: rteller/nginx_echo
        name: echo
        ports:
        - containerPort: 8200