apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-echo
spec:
  replicas: 2
  selector:
    matchLabels:
      app: nginx-echo
  template:
    metadata:
      labels:
        app: nginx-echo
    spec:
      containers:
      - image: rteller/nginx_echo
        name: echo
        ports:
        - containerPort: 8200
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: nginx-echo-svc
  name: nginx-echo-svc
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 8200
  selector:
    app: nginx-echo